### ISSUE TITLE
[SUGGESTION] WZS: Command to force players into  VC channels

### ISSUE THREAD

**Issue by Peppernip** [Azurblau/Zombies.Zone#17] opened 2018-02-08 05:03 UTC
Would it be possible to make a command which would force players into their own VC Channel?

**Comment by WardenPotato** [comment] 2018-04-02 22:31
Would be good

**Comment by CWorm** [comment] 2018-04-03 13:18
Duplicate of #86  which is assigned now, closing.

**Closed by CWorm** 2018-04-03 13:18 UTC
